### PR TITLE
path-rootless considers invalid segments

### LINKED ISSUE #665: Crash with invalid url
The following Program reproduces a crash: 

```console
a.out: /usr/local/include/boost/url/detail/path.hpp:82: std::size_t boost::urls::detail::path_segments(boost::urls::string_view, std::size_t): Assertion `nseg == 0' failed.
Aborted
```

```cpp
#include <boost/url/src.hpp>
#include <iostream>
int main(void) {
  try {
    boost::urls::url_view u("A:\\");
  } catch (...) {
    std::cout << "exception caught" << std::endl;
  }
  std::cout << "bye." << std::endl;
  return 0;
}

```

### PR DESCRIPTION
**Pull request by alandefreitas**
fix #665

### CODE REVIEW

File: test/unit/parse.cpp [hunk 1]
```diff
@@ -23,9 +23,20 @@ struct parse_test
...
         }
+        // issue 665
+        {
+            {
+                auto r = parse_uri_reference("A:\\");
+                BOOST_TEST_THROWS(r.value(), system_error);
+            }
+            {
+                auto r = parse_uri_reference("A:\"");
+                BOOST_TEST_THROWS(r.value(), system_error);
```
Comment (vinniefalco) [inline test/unit/parse.cpp:37]: Great :)

File: test/unit/parse.cpp [hunk 2]
```diff
@@ -23,9 +23,20 @@ struct parse_test
         // issue 497
         {
             auto r = parse_uri_reference("?~");
-            BOOST_TEST_NO_THROW(r);
+            BOOST_TEST_NO_THROW(r.value());
```
Comment (vinniefalco) [inline test/unit/parse.cpp:26]: oops

Comment (alandefreitas) [reply test/unit/parse.cpp:26]: :)
